[package]
name = "rg"
version = "0.1.0"
authors = ["newbe36524 <newbe36524@qq.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
regex = "1.10.2"
serde = { version = "1.0.190", features = ["derive"] }
anyhow = "1.0.75"
thiserror = "1.0"
log = "0.4.20"
env_logger = "0.10.0"
tokio = { version = "1.33.0", features = ["full"] }
cmd_lib = "1.6.1"
async-trait = "0.1.74"
appinsights = "0.2.3"

[dev-dependencies]
rstest = "0.18.2"
async-std = { version = "1.12", features = ["attributes"] }