[package]
name = "rg"
version = "0.1.0"
authors = ["newbe36524 <newbe36524@qq.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde_json = "1.0.99"
serde_yaml = "0.9.22"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
anyhow = "1.0.71"
thiserror = "1.0"
log = "0.4.19"
env_logger = "0.10.0"
tokio = { version = "1.28.2", features = ["full"] }
cmd_lib = "1.3.0"
async-trait = "0.1.68"
appinsights = "0.2.3"

[dev-dependencies]
rstest = "0.17.0"
async-std = { version = "1.12", features = ["attributes"] }