[package]
name = "rg"
version = "0.1.0"
authors = ["newbe36524 <newbe36524@qq.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
reqwest = { version = "0.11.14", features = ["json"] }
serde_json = "1.0.93"
serde_yaml = "0.9.17"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
anyhow = "1.0.69"
thiserror = "1.0"
log = "0.4.17"
env_logger = "0.10.0"
tokio = { version = "1.25.0", features = ["full"] }
cmd_lib = "1.3.0"
async-trait = "0.1.64"
appinsights = "0.2.3"

[dev-dependencies]
rstest = "0.16.0"
async-std = { version = "1.12", features = ["attributes"] }

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
ar = "x86_64-apple-darwin14-ar"