[package]
name = "rg"
version = "0.1.0"
authors = ["newbe36524 <newbe36524@qq.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
reqwest = { version = "0.11.20", features = ["json"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
regex = "1.9.3"
serde = { version = "1.0.186", features = ["derive"] }
anyhow = "1.0.75"
thiserror = "1.0"
log = "0.4.20"
env_logger = "0.10.0"
tokio = { version = "1.32.0", features = ["full"] }
cmd_lib = "1.3.0"
async-trait = "0.1.73"
appinsights = "0.2.3"

[dev-dependencies]
rstest = "0.18.2"
async-std = { version = "1.12", features = ["attributes"] }