name: Build and Release Rust Binary
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            file_name: rg
          - target: aarch64-unknown-linux-gnu
            file_name: rg
          - target: x86_64-pc-windows-gnu
            file_name: rg.exe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
      - run: |
          cargo install cross
          cd src
          cross build --target ${{ matrix.target }} --release
          mv ./target/${{ matrix.target }}/release/${{ matrix.file_name }} ./${{ matrix.target }}-${{ matrix.file_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src/${{ matrix.target }}-${{ matrix.file_name }}
